### PR TITLE
Convert Teams page to a NextJS layout

### PR DESCRIPTION
**Pull request by Oksamies**

### CODE REVIEW

**Comment by Oksamies** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1031?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #1023** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1023?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1024** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1024?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1029** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1029?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1030** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1030?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1031** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1031?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
            * **PR #1032** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1032?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1031?utm_source=stack-comment).

**Review by anttimaki — COMMENTED** [review]
Does this contain all the intended files? It's doesn't seem so much a conversion, but adding of new pages and leaving the old Layout-component to rot in @thunderstore/cyberstorm?

Other than that, comments given on https://github.com/thunderstore-io/thunderstore-ui/pull/1024 apply here too. I've nothing else to add.

**Comment by Oksamies** [comment]
I'll remove the old layouts in a separate PR

**Comment by Oksamies** [comment]
### Merge activity

* **Feb 8, 8:22 AM EST**: @Oksamies started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1031).

**Pull request merged**
