### PR TITLE
Internalize "Button to Anchor" logic into Button component

### PR DESCRIPTION
**Pull request by Oksamies**
Internalize "Button to Anchor" logic into Button component

Sometimes Button might be used as a link and in these cases we
want to have Button component as <a> instead of div wrapped with <a>

Fix "Get Manager" buttons

Remove anchor wrappers
Fix styles to be up to specs

### CODE REVIEW

**Comment by Oksamies** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1007?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #998** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/998?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1005** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1005?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
      * **PR #1006** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1006?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1007** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1007?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
          * **PR #1008** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1008?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1007?utm_source=stack-comment).

**Review by anttimaki — APPROVED** [review]
This works so I'm approving it. But I'm not a fan of it 😏 But it's probably faster to do a PR myself that try to explain my thoughts. However, the takeaways for the future:

- It's less than ideal to have (an undocumented) `href` prop that only works if also (an undocumented) `plain` prop is passed. I'd say generally this is a sign that your component is trying to do too many things and should be split to separate components
- The amount of repetition is unnecessarily high even if we would want to keep all the stuff in one component (especially the long props list)
- There's no need to nest the if-statements in this case. At least IMO it makes the code harder to follow, and makes it harder to keep line-lengths in check. In this case since we return early anyway, it could be just:

```
if plain and href
  return anchor
if plain
  return div
return button
```

**Comment by Oksamies** [comment]
Oh yeah, definitely a bad component right now. Decided to not go refactor it, since that would block the page launch and in the end the refactor probably would not affect UX in anyway right now at least. I'll try to make some time for this tomorrow though.

**Comment by Oksamies** [comment]
### Merge activity

* **Jan 17, 7:32 AM**: @Oksamies started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1007).

**Comment by anttimaki** [comment]
@Oksamies

> I'll try to make some time for this tomorrow though.

Don't, I'm working on it already.

**Pull request merged**
