### PR TITLE
@thunderstore/sertra: server detail page related refactoring

### PR DESCRIPTION
**Pull request by anttimaki**
In bite-sized commits for your reviewing pleasure.

### CODE REVIEW

**Comment by anttimaki** [comment]
Current dependencies on/for this PR:
* master
  * **PR #510** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/510" target="_blank">Graphite</a> 
    * **PR #511** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/511" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/511?utm_source=stack-comment).

**Review by Oksamies — APPROVED** [review]
There was some linter alert, but other than that, all of this looks good to me 👍

**Comment by anttimaki** [comment]
> There was some linter alert, but other than that, all of this looks good to me 👍

Yeah I know, it was introduced [by your PR](https://github.com/thunderstore-io/thunderstore-ui/pull/481) 😜 But like Mythic mentioned on the ticket, it makes sense to focus on fixing the disparity between the ESLint config and the automatic linting done by precommit, rather than fix these by hand. (Although I was tempted to fix it anyway.)

**Comment by anttimaki** [comment]
@MythicManiac care to merge this, I seem to lack the privileges due to CI going red.

**Pull request merged**
