### PR TITLE
Make sure page Header stays on top

### PR DESCRIPTION
**Pull request by Oksamies**
Make sure page Header stays on top of page contents effects, etc

### CODE REVIEW

**Comment by Oksamies** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1005?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `master`
  * **PR #998** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/998?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #1005** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1005?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈
      * **PR #1006** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1006?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
        * **PR #1007** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1007?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
          * **PR #1008** <a href="https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1008?utm_source=stack-comment-icon" target="_blank">Graphite</a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1005?utm_source=stack-comment).

**Review by anttimaki — COMMENTED** [review]
I'm not 100% sure this due to the change here, but all the content of the Header disappears on narrow screens. The Header background remains, but buttons etc. are gone.

**Comment by Oksamies** [comment]
> I'm not 100% sure this due to the change here, but all the content of the Header disappears on narrow screens. The Header background remains, but buttons etc. are gone.

That is actually an existing issue/feature. Basically there is width boundary set for the header, but no replacing "mobile header" is implemented.

I didn't do smaller screen responsivity yet. That's todays agenda, after getting most of this stack merged and through the build pipeline.

**Comment by Oksamies** [comment]
### Merge activity

* **Jan 17, 7:32 AM**: @Oksamies started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/thunderstore-io/thunderstore-ui/1005).

**Pull request merged**
